### ISSUE TITLE
Destructuring

### ISSUE THREAD

**Issue by azu** [asciidwango/js-primer#113]
#17 基本文法

Destructuringについて扱う。
<del>Destructuringは他と組み合わせ使う傾向があるけど、一見するとよくわからないものなので一つの文法として紹介した方が良さそう。</del>

- 細かいユースケースについては、他の文法の紹介時に含めるような形にする
- `Promise.all`
- module (これ実は構文として違うんだろなー)
- オプションオブジェクト (これは後半のユースケースでも出てくる?)

など色々あるが、基本的な配列とオブジェクトの2種類を紹介する形にする。

追記: 2018-12-16

- 基本的な形は[演算子](https://jsprimer.net/basic/operator/)の`=`で紹介する
- 配列、オブジェクト、関数 においてそれぞれ軽くDestructuringについて扱う

という程度に留めておく。

## 目的

分割代入（Destructuring assignment）という構文の名前を知ること。
初めてみたときこの構文は混乱するので、この名前を知っていればあとはMDNなど色々なリソースでより詳細な構文を知ることができるという点を目的としている。 分割代入（Destructuring assignment）をすべて解説しないで、最低限(オブジェクト、配列、関数)だけに絞ってははなす。

オブジェクトについては、モジュールでも同じような構文となるため目に慣れておいて欲しいという点も含めて何箇所かにだしている。

## Tasks

- [x] 演算子と暗黙的な型変換の章を移動(配列、オブジェクト、関数より前) #589
- [x] [演算子](https://jsprimer.net/basic/operator/)の`=`で紹介
- [x] 配列で `const [a, b] = [1, 2]` を紹介 #593
- [x] オブジェクトで `const {a, b} = { a: 1, b: 2 }` を紹介 #593
- [ ] 関数の引数での分割 `Object.entries({}).map(([key, value]) => {})`

**Comment by azu** [comment]
Destructuringは異様に複雑なことも書けるので、ほどほどというものを上手く言葉にまとめたい感じ。

- [ES6 Destructuring Recipes | Untangled](http://untangled.io/es6-destructuring-recipes/)
- [The Most In-Depth Yet Understandable ES6 Destructuring Tutorial (complete with Assembled Avengers) | Untangled](http://untangled.io/in-depth-es6-destructuring-with-assembled-avengers/)

以前、仕様の議論でも以下のはOKなの?とか色々話がでていたので、特殊な使い方より普通の人が普通に使うパターンについて解説したい

```js
var obj = {};
let { } = obj;
``

- [Destructuring declarations that bind nothing should probably be an early error · Issue #97 · tc39/ecma262](https://github.com/tc39/ecma262/issues/97#issuecomment-150275054)

**Comment by azu** [comment]
他の言語では多重代入と言われてたりする。
やっぱりルールが複雑化しやすいのは同じっぽい

- [複数の値をまとめて代入(多重代入) | タプル | プログラミング言語の比較 | hydroculのメモ](https://hydrocul.github.io/wiki/programming_languages_diff/tuple/multiple-assignment.html "複数の値をまとめて代入(多重代入) | タプル | プログラミング言語の比較 | hydroculのメモ")

**Comment by yumetodo** [comment]
C++だとC++17に提案されている
[P0341R0: Leveraging parameter packs outside of templates](https://cpplover.blogspot.jp/2016/08/c-p0340r0-p0349r0.html)
とか
C++17入りが決定した
[P0217R2: Wording for structured bindings](https://cpplover.blogspot.jp/2016/06/c-p0210r0-p0219r0.html)
が該当しますかねぇ

**Comment by azu** [comment]
[My New Favorite ES6 Toy: Destructured Objects as Parameters | CSS-Tricks](https://css-tricks.com/new-favorite-es6-toy-destructured-objects-parameters/ "My New Favorite ES6 Toy: Destructured Objects as Parameters | CSS-Tricks")

**Comment by azu** [comment]
- [演算子](https://jsprimer.net/basic/operator/)の`=`で紹介
- 配列で `const [a, b] = [1, 2]` を紹介
- オブジェクトで `const {a, b} = { a: 1, b: 2 }` を紹介
- [ ] 関数の引数での分割 `Object.entries({}).map(([key, value]) => {})`
  - 適当な場所がない気がする

**Comment by azu** [comment]
📝 `=` と 関数のDestructuringは構文的には異なる定義

- https://tc39.github.io/ecma262/#prod-AssignmentPattern
- https://tc39.github.io/ecma262/#prod-BindingPattern
