### ISSUE TITLE
ECMAScript 2020の対応

### ISSUE THREAD

**Issue by azu** [asciidwango/js-primer#1145]
ECMAScript 2020のリリース候補がでたので、どうするか検討する。

- [ECMAScript 2020: the final feature set](https://2ality.com/2019/12/ecmascript-2020.html)
- [proposals/finished-proposals.md at master · tc39/proposals](https://github.com/tc39/proposals/blob/master/finished-proposals.md)

この書籍の目的としては現実のユースケースを反映することであって、リファレンスになることが目的ではない。
そのため、仕様に入っても追加しないという判断もあるので、ここのProposalごとに決めていく必要がある。

## Proposals

- [x]  for-in mechanics #1180 
- [x] export * as ns from "mod"; #1177 
- [x] `String.prototype.matchAll` #1182 #1250 
- [x] `globalThis` #1181 
- [x] BigInt #445 
- [x] Nullish coalescing Operator #1178 
- [x] Optional chaining #1179 
- [x] <del>`Promise.allSettled`</del> 非対応
- [x] `import()` ユースケースが思いついたら
- [x] `import.meta`
- [x] チートシート #1204 #1247 

BigInt(プリミティブの種類)、globalThis(thisの説明)、Nullish coalescing Operator(デフォルト引数)、 Optional chaining(undefined?まわり)あたりは必要になる気がする。

## 対応後

- [x] https://github.com/asciidwango/js-primer/blob/93421692481e11bf42d5ca78ccf14e4b539b267d/book.json#L22 を更新する

追記: 

対応するべきものはIssueを個別に切ったので、やりたい人がいたらコメントしてください。
https://github.com/asciidwango/js-primer/labels/good%20first%20issue は簡単なIssueです。

**Comment by azu** [comment]
[What's new in ECMAScript 2020 | Strict Mode](https://www.strictmode.io/articles/whats-new-es2020/)

**Comment by azu** [comment]
https://www.ecma-international.org/news/index.html
ES2020が正式にリリースされた

**Comment by azu** [comment]
現実的な話としてはFirefoxも対応してないと使えない(試せない)ということがあるので、
対応するかは次の基準が入る

- 大体のブラウザで動く
- ユースケースがある程度見えているものである
- 既存の説明に齟齬がでる変更(BigIntとかはプリミティブなので未対応でも入れるべき)

**Comment by azu** [comment]
まずは、どの項目から対応する(対応できる)かの一覧を作る

**Comment by azu** [comment]
[ES2020: ` export * as ns from "mod";`の対応 · Issue #1177 · asciidwango/js-primer](https://github.com/asciidwango/js-primer/issues/1177)
は一行追加するだけだし、対応して良さそう

**Comment by azu** [comment]
## Nullish coalescing Operator

[Null合体演算子 - JavaScript | MDN](https://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Operators/Nullish_coalescing_operator) 
合体という訳は微妙な気がするけど、これはデフォルト引数の `||` の問題を解決する話、[falsy](https://jsprimer.net/basic/implicit-coercion/)の話と関係するので入れるのは妥当な気がする。

https://jsprimer.net/basic/function-declaration/#function-default-parameters

[falsy](https://jsprimer.net/basic/implicit-coercion/)の話題自体は`if`文と関係するから残るはず。
`||` での判定の問題にフォーカスするのがいい気がする。
デフォルト引数の解決のパターンとして並べるのが妥当かもしれない?
演算子に入るイメージはあんまりないのかも。演算子が肥大化するから、一旦演算子の章を整理して必須じゃないものは全部消すとかしてもいい。

**Comment by azu** [comment]
## Optional chaining

[Optional chaining - JavaScript | MDN](https://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Operators/Optional_chaining)

https://jsprimer.net/basic/object/#confirm-property でまさにその事例があるので、ここで紹介する。
#1178 Nullish coalescing Operatorとの組み合わせについても紹介するといいのかもしれない?
ユースケースでこういう箇所あるかな?

**Comment by azu** [comment]
## for-in mechanics

> for...in文はオブジェクトのプロパティに対して、順不同で反復処理を行います。
https://jsprimer.net/basic/loop/#for-in-statement

これが仕様で定義されるようになったので、<del>順不同で</del>とすればOKそう。
footerでES2020で順番が定義されたことについて追加する

Issue: #1180

**Comment by azu** [comment]
## globalThis

globalThis - JavaScript | MDN

    ブラウザならwindowオブジェクト、Node.jsならglobalオブジェクトとなります。
    https://jsprimer.net/basic/function-this/#execution-context-this

これをまとめた概念としてglobalThis がES2020で追加されたことについてを追加する。

Issue: https://github.com/asciidwango/js-primer/issues/1181

**Comment by azu** [comment]
## Promise.allSettled()

[tc39/proposal-promise-allSettled: ECMAScript Proposal, specs, and reference implementation for Promise.allSettled](https://github.com/tc39/proposal-promise-allSettled)

ユースケースがちょっと出てこない

Promise本では網羅的に対応するべきだけど、JS Primerだといらないかもしれない。
わざと失敗しても取得したいケースみたいな例示にしかできない感じ。
[Promise.allSettled (ES2020) · Issue #330 · azu/promises-book](https://github.com/azu/promises-book/issues/330)

**Comment by azu** [comment]
## BigInt 

プリミティブ型と整数のところで紹介する。
実際の使い方まではやらない気がする。Mathがあまりにも弱いので、BigIntだけ対応しても微妙。
Math自体の強化と合わせて考えてやる必要がある

Issue #445

**Comment by azu** [comment]
## ` String.prototype.matchAll`

https://jsprimer.net/basic/string/#match-by-regexp
でexecを使ったmatchAllを実装している。
これをmatchAllを使ったやり方を紹介する。
exec自体はよく見かけるから、残す感じがする。
matchAll自体をセクションとして入れるとか?

[String.prototype.matchAll() - JavaScript | MDN](https://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Global_Objects/String/matchAll)

**Comment by azu** [comment]
## import() と import.meta

ユースケースででてきてないので微妙かもしれない。
ユースケースの範囲で対応してないと出す意味はない気がする。
これが必要になるのは、なんかもうちょいアプリがでかい場合な気がする。

**Comment by azu** [comment]
一応それぞれ対応予定のIssueを作りました /cc @lacolaco

**Comment by azu** [comment]
[付録: JavaScriptチートシート · JavaScript Primer #jsprimer](https://jsprimer.net/cheetsheet/)
チートシートも対応する https://github.com/asciidwango/js-primer/issues/1204

**Comment by azu** [comment]
Dynamic Import も対応したいけど、これECMAScriptの章自体を書き換えないと行けない気がする。
このIssueとは別でやった方がよさそう。(ECMAScriptの章を実行可能な状態でやりたい感じ)

**Comment by azu** [comment]
> JavaScriptのすべての文法や機能を網羅するのが目的ではない
> JavaScriptのリファレンスとなることが目的ではない
> [本書の目的ではないこと](https://jsprimer.net/intro/#do-not)

この辺をちゃんと把握して進められるようにするため、新しく項目増やすときにチェックする項目がほしい感じ。

**Comment by azu** [comment]
[Features tagged “ES2020” · V8](https://v8.dev/features/tags/es2020)
V8のブログが結構まとまっているので良さそう

**Comment by azu** [comment]
ES2020は全て対応できた 🎉 

あとはバージョンとリリースノートを書く
