### ISSUE TITLE
JavaScript Primer 発売開始

### ISSUE THREAD

**Issue by azu** [asciidwango/js-primer#1152]
4/27でJavaScript Primerの書籍版が購入できるようになる

- https://www.amazon.co.jp/dp/4048930737/

発売開始周りのタスクを管理するIssue。

## TODO

- [x] ブログを書く https://efcl.info/2020/04/27/jsprimer/
- [x] メーリングリストでの通知 https://mailchi.mp/17b99e1c3bf1/javascript-primer
- [x] 電子書籍版のページへのリンク https://tatsu-zine.com/books/javascript-primer

**Comment by azu** [comment]
epubなどもは発売できたので閉じます。
