### ISSUE TITLE
書籍版の正誤表の管理

### ISSUE THREAD

**Issue by azu** [asciidwango/js-primer#1159]
書籍版(`publish1`)への修正をどう管理するかについて決める

- [x] 修正内容は `publish1` に反映する
  - これは #1154 のミーティングで `publish1` にコミットするでOKになった
- [ ] 修正内容の管理(いわゆる正誤表てきなの)は必要? (何ページ目の~を修正みたいな)
- [ ] 修正した/修正してないを誰がどう管理するか
  - Markdownの方でPRきてわかる場合があるので、これをTeXに反映するのはだれがやるか?

## 取り込む必要があるもの

- [ ] [chore: fix typo by hasebe · Pull Request #1158 · asciidwango/js-primer](https://github.com/asciidwango/js-primer/pull/1158)
- [ ] [chore: fix typo in statement-expression by nobu09 · Pull Request #1160 · asciidwango/js-primer](https://github.com/asciidwango/js-primer/pull/1160)
- [ ] [fix(data-type): keyをクオートで囲むように by azu · Pull Request #1168 · asciidwango/js-primer](https://github.com/asciidwango/js-primer/pull/1168)

**Comment by azu** [comment]
[chore: fix typo by hasebe · Pull Request #1158 · asciidwango/js-primer](https://github.com/asciidwango/js-primer/pull/1158)
この修正はTeXの方に反映しないといけないので、こういうのを今後どう/いつまで管理するかというIssueです。
https://github.com/asciidwango/js-primer/blob/17957b024e4e8e833314d1a12f0e79115536aa9c/TeX/chap32.tex#L2241

**Comment by azu** [comment]
反映が必要なPRに対して特定のラベルをつけてそれで管理するとかもあり(楽ではある)

**Comment by azu** [comment]
とりあえず、反映したほうがいいものは [label:"Type: Need to Publish"](https://github.com/asciidwango/js-primer/issues?q=label%3A%22Type%3A+Need+to+Publish%22+)をつけました

**Comment by kahei** [comment]
azuさん、どうもありがとうございます。
やはりラベルをつけて管理するのがシンプルでいいような気がします。
