### ISSUE TITLE
ES2021の対応

### ISSUE THREAD

**Issue by azu** [asciidwango/js-primer#1220]
ECMAScript 2021対応のmeta issueです。

[proposals/finished-proposals.md at master · tc39/proposals](https://github.com/tc39/proposals/blob/master/finished-proposals.md)

## やりかた

- 検討リストから対応するべきかを決める
- 対応するものは別途Issue化する
- 対応する
- [x] すべて対応したら `book.js` を更新

## 検討リスト

- [x] [String.prototype.replaceAll](https://github.com/tc39/proposal-string-replaceall) #1310 
- [x] [Numeric Separators](https://github.com/tc39/proposal-numeric-separator) #1311 
- [x] [Promise.any + AggregateError](https://github.com/tc39/proposal-promise-any)
- [x] [WeakRefs](https://github.com/tc39/proposal-weakrefs)
- [x] [Logical Operators and Assignment Expressions](https://github.com/tc39/proposal-logical-assignment)

## 過去

-  ECMAScript 2020の対応 #1145

**Comment by azu** [comment]
[Feature watch: ECMAScript 2021](https://2ality.com/2020/09/ecmascript-2021.html)

**Comment by azu** [comment]
- [ECMAScript 2021: the final feature set](https://2ality.com/2020/09/ecmascript-2021.html)
  - [Release ES2021 Candidate March 2021 · tc39/ecma262](https://github.com/tc39/ecma262/releases/tag/es2021-candidate-2021-03)

ES 2021 CRがでた

**Comment by azu** [comment]
Related

- [ES2021 edition of “JavaScript for impatient programmers”](https://gist.github.com/rauschma/e9c00fddc17e73fab6ce6c22b2e78e17)

**Comment by azu** [comment]
# String.prototype.replaceAll 

#1182 はES2020で、ES2021でreplaceAll

> replaceメソッドには正規表現も指定できます。 gフラグを有効化した正規表現を渡すことで、文字列からパターンにマッチするものをすべて置換できます。
> https://jsprimer.net/basic/string/#replace-delete

があるので、これの別解としてreplaceAllは追加するのが妥当。
用途的には正規表現を使わずにすべてを置換したい場合となる。
正規表現も渡せるが /g がないとエラーとなることについて触れる。

[Regular expressions (`RegExp`) • JavaScript for impatient programmers (ES2021 edition)](https://exploringjs.com/impatient-js/ch_regexps.html#replace-replaceAll)

**Comment by azu** [comment]
# [Promise.any + AggregateError](https://github.com/tc39/proposal-promise-any)

最初に成功したものを得る Promise.any 。
投機的に複数走らせて最初に取れたものがいいみたいな状態

- [Promises for asynchronous programming \[ES6\] • JavaScript for impatient programmers (ES2021 edition)](https://exploringjs.com/impatient-js/ch_promises.html#Promise.any)

これはユースケースではでてこなから取り扱わなくてもいい気がする。
一方で、全てがエラーの場合は`AggregateError`を返すという複数エラーの扱い方が追加されている。
この `AggregateError` 自体は [例外処理 · JavaScript Primer #jsprimer](https://jsprimer.net/basic/error-try-catch/) に入れてもいいかもしれない。

保留な感じがする

**Comment by azu** [comment]
# [WeakRefs](https://github.com/tc39/proposal-weakrefs)

WeakMapとWeakSetの章はあるけど、Weakの話を追加するほどじゃない気はする。
これはskipすると思う。advancedな感じがする

**Comment by azu** [comment]
# [logical-assignment](https://github.com/tc39/proposal-logical-assignment)

```js
// "Or Or Equals" (or, the Mallet operator :wink:)
a ||= b;
a || (a = b);

// "And And Equals"
a &&= b;
a && (a = b);

// "QQ Equals"
a ??= b;
a ?? (a = b);
```

が増える。
基本的に再代入でしかないので、結構扱いが難しい気がする。

```js
function printWidgetTitle(widget) {
    const title = widget?.window?.title ?? "未定義";
    console.log(`ウィジェットのタイトルは${title}です`);
}
printWidgetTitle({
    window: {
        title: "Book Viewer"
    }
}); // "ウィジェットのタイトルはBook Viewerです" と出力される
printWidgetTitle({
    // タイトルが定義されてない空のオブジェクト
}); // "ウィジェットのタイトルは未定義です" と出力される
```

は

```js
function printWidgetTitle(widget) {
    widget.title ??= "未定義";
    console.log(`ウィジェットのタイトルは${widget.title}です`);
}
printWidgetTitle({});
```

みたいな感じにするとかはありそうだけど、次のようには書けないので微妙。
そもそもオブジェクトに再代入してる時点で、引数で受け取ったオブジェクトを書き換えてるので良くない(どこかのコラムでそういうのを書いてた気がする?)

```js
function printWidgetTitle(widget) {
    widget?.window?.title ??= "未定義";
    console.log(`ウィジェットのタイトルは${title}です`);
}
printWidgetTitle({
    window: {
        title: "Book Viewer"
    }
}); // "ウィジェットのタイトルはBook Viewerです" と出力される
printWidgetTitle({
    // タイトルが定義されてない空のオブジェクト
}); // "ウィジェットのタイトルは未定義です" と出力される
```

検索のために、[付録: JavaScriptチートシート · JavaScript Primer #jsprimer](https://jsprimer.net/cheatsheet/)に入れるのはありだけど、本文にはあんまり入れるユースケースが思いつかない

**Comment by azu** [comment]
# [Numeric Separators](https://github.com/tc39/proposal-numeric-separator)

```


let budget = 1_000_000_000_000;

// What is the value of `budget`? It's 1 trillion!
// 
// Let's confirm:
console.log(budget === 10 ** 12); // true
```

区切り文字に `_` を使えるよってだけ。見た目だけ

- https://jsprimer.net/basic/data-type/#Bigint-literal
- [付録: JavaScriptチートシート · JavaScript Primer #jsprimer](https://jsprimer.net/cheatsheet/)

にそれぞれ追加するぐらいで良いかもしれない。

あと https://jsprimer.net/basic/operator/#bit-operator ビット演算の所でこれを使って見やすくするとか良さそうなきがするので、検討する

**Comment by azu** [comment]
- String.prototype.replaceAll #1310
- Numeric Separators #1311 

それぞれIssueを作った

**Comment by azu** [comment]
https://github.com/asciidwango/js-primer/issues/1220#issuecomment-832400626
リリースノートへのリンクみたいのどうするかちょっと迷うな。
この書籍は網羅が目的じゃないので、ESバージョンとはあんまり対応してない

**Comment by azu** [comment]
[Ecma International approves new standards - Ecma International](https://www.ecma-international.org/news/ecma-international-approves-new-standards-4/) でES2021は正式に商人された

**Comment by azu** [comment]
> [logical-assignment](https://github.com/tc39/proposal-logical-assignment)

https://jsprimer.net/basic/operator/#assignment-operator で 他の += とかは紹介しるので、入れるのはありだけど(サンプルコードはない)、どうするべきかなー
演算子はやっぱり無限に膨れるので、次のタイミングで削りたい
