### ISSUE TITLE
ES2022: StringとArrayの `.at()`

### ISSUE THREAD

**Issue by azu** [asciidwango/js-primer#1367]
## `.at()`

追加する。

- https://jsprimer.net/basic/array/#create-and-access でインデックスだけではなく `.at()` についても追加する (length -1 のケースはatだと -1 とかける)
- https://jsprimer.net/basic/string/#get-char Stringでもインデックスに加えて `.at()` について触れる
- https://jsprimer.net/basic/class/#extends-built-in で firstとlastという題材も扱ってるので `.at()` を使うようにする

基本的に `length - 1` は `.at()` に置き換える。

DOM APIについては、item() 名前は標準化失敗した気がするし、触れなくて良い気がする。

https://github.com/tc39/proposal-relative-indexing-method#dom-justifications
https://developer.mozilla.org/ja/docs/Web/API/NodeList/item

_Originally posted by @azu in https://github.com/asciidwango/js-primer/issues/1337#issuecomment-1000675212_

## TODO

- [ ] https://github.com/asciidwango/js-primer/issues/1367#issuecomment-1019061549

**Comment by azu** [comment]
Refs

- [String.prototype.at() - JavaScript | MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/at)
- [Arrays (`Array`) • JavaScript for impatient programmers (ES2022 edition)](https://exploringjs.com/impatient-js/ch_arrays.html#Array.prototype.at)

**Comment by azu** [comment]
## 調査

- [ ] `array[-1]` がどうなるかの解説があるか
- [ ] `.at(-1)` 以外のユースケースがあるか
- [ ] 仕様のアルゴリズム調査
	- そのままの動き? [tc39/proposal-relative-indexing-method: A TC39 proposal to add an .at() method to all the basic indexable classes (Array, String, TypedArray)](https://github.com/tc39/proposal-relative-indexing-method#polyfill)

**Comment by azu** [comment]
>  書籍内で array[-1] がどうなるかの解説があるか

> 配列のlengthプロパティは配列の要素の数を返します。 そのため、配列の最後の要素へアクセスするには array.length - 1 をインデックスとして利用できます。

が近いけど。
インデックスアクセスが`at()`によって全て置き換わるとは思えないので、

Array.prototype.at というセクションを足すのが無難かなー
length - 1 もdeprecatedといえるほどまだ浸透していないし、関数callだからコストはどうなんだろとかある

**Comment by azu** [comment]
>  .at(-1) 以外のユースケースがあるか

ほぼこれ一択な感じがする

**Comment by azu** [comment]
## やること

- [ ]  https://jsprimer.net/basic/array/#create-and-access の次に `Array#at` というセクションを追加する
   - `length - 1` と書いていたけど、ES2022ではatが追加されました
   - `at(-1)` と `length - 1` は同等の意味です。
   - なぜatが追加されたかというと
     - `[-1]`は `"-1"` というプロパティアクセスになるため、最後の要素にアクセスするのには使えません。
     - 最後の要素にアクセスにlength -1 を使うと2回arrayを参照する必要があって手間です。
     - 最後の要素にアクセスというわかりやすい方法として at が導入されました
- [ ]  https://jsprimer.net/basic/string/#get-char String#atのセクションを追加する
    - 配列とほぼ同じです
    - at(0)とかat(-1) でアクセスできますというコード例だけで十分
- [ ]  https://jsprimer.net/basic/class/#extends-built-in で firstとlastという題材も扱ってるので .at() を使うようにする

**Comment by azu** [comment]
https://github.com/asciidwango/js-primer/issues/1163
sliceも若干関係する話に思えてきた。
