### ISSUE TITLE
Node.js 18 LTSに更新する

### ISSUE THREAD

**Issue by azu** [asciidwango/js-primer#1437]
https://github.com/nodejs/release#release-schedule

Node.js 18 LTSは2022-10-25にリリースされる。

LTSがリリースされるタイミングで変更する

## TODO

- [x] このリポジトリ自体をnpm8で動くようにする(lockのアップデート、https://github.com/asciidwango/js-primer/blob/master/.nvmrc 、CI周り)
- [x] npx がインタラクティブになった変更する `-y` を使う? #1484 
  - https://jsprimer.net/use-case/setup-local-env/
- [x] 2022-10-25まで待つ
- [ ] Node.js 18に変更
- [ ] npm 8に変更

やることは、次のPRのNode.js 18版(本文的にはいじる場所がない)

- https://github.com/asciidwango/js-primer/pull/1486

CI的には一応Node 16, 18でも問題ないので、CIは変更しなくてよささそう。

## 過去の変更

- #1484 
- #1265 
- #976

**Comment by azu** [comment]
`node:assert` とかの変更を検討する

**Comment by azu** [comment]
npm 8になるのでpackage-lock.jsonの変更があるかを確認する
`npm -v ` は変更する

**Comment by azu** [comment]
https://jsprimer.net/use-case/setup-local-env/#npx-execution
`npx` の メッセージを変更する

**Comment by azu** [comment]
先にこのリポジトリ自体をnpm 8 で動かすようにしたい。

**Comment by azu** [comment]
LTSになるのはNode 18だった

- [ ] 16にあげる
- [ ] npxの対応

と

- [ ] 18にあげるを分けてやる

**Comment by azu** [comment]
Node.js  18 LTSは2025-04-30までメンテナンスされる。

**Comment by azu** [comment]
[npm v9.0.0 released | GitHub Changelog](https://github.blog/changelog/2022-10-24-npm-v9-0-0-released/)
によると1月18日水曜日にNode 18にもnpm 9が来るので、これはどうするか微妙に面倒な感じ。
とりあえずNode 18 LTSまでは上げるでいいと思うけど

**Comment by azu** [comment]
[Node v18.12.0 (LTS) | Node.js](https://nodejs.org/en/blog/release/v18.12.0/)
リリースされた
