### ISSUE TITLE
anonymous functionの訳語について（匿名関数 or 無名関数）

### ISSUE THREAD

**Issue by kawanohiroki** [asciidwango/js-primer#1650]
URL : https://github.com/asciidwango/js-primer/blob/master/source/basic/function-declaration/README.md

たいへん有益なドキュメントを提供してくださって本当にどうもありがとうございます。
文書中でanonymous functionの訳語として主として「匿名関数」を採用していると認識していますが、「匿名」だと日本語では名前があるけれどそれを秘匿しているという意味になるので、「無名関数」のほうが訳語としてより妥当性が高いように思いました。
ご検討いただけるようであればさいわいです。

**Comment by azu** [comment]
ありがとうございます。特に強い意図はなく匿名関数に統一してた気はするので、無名関数の方に寄せるでいいかもしれないですね。

仕様もAnonymouse Functionなので、無名関数の方が良さそうな気がします。
https://tc39.es/ecma262/#sec-isanonymousfunctiondefinition

この部分を逆転させて、
https://github.com/asciidwango/js-primer/blob/4bb3c4c6fd8b76ce99c6df31892ee44cd87cf37e/source/basic/function-declaration/README.md?plain=1#L459
辞書で管理してるので、これも逆にするのが良さそうです。
https://github.com/asciidwango/js-primer/blob/4bb3c4c6fd8b76ce99c6df31892ee44cd87cf37e/prh.yml#L137-L138


## TODO

- [ ] https://github.com/asciidwango/js-primer/blob/4bb3c4c6fd8b76ce99c6df31892ee44cd87cf37e/source/basic/function-declaration/README.md?plain=1#L459 を逆にする
- [ ] https://github.com/asciidwango/js-primer/blob/4bb3c4c6fd8b76ce99c6df31892ee44cd87cf37e/prh.yml#L137-L138 辞書も逆にして、`npm run textlint:fix`
- [ ] コードで"匿名関数"と言ってる箇所があるので手動で置換
