### ISSUE TITLE
ECMAScript 2023の対応

### ISSUE THREAD

**Issue by azu** [asciidwango/js-primer#1658]
ECMAScript 2023対応のmeta issueです。

[proposals/finished-proposals.md at master · tc39/proposals](https://github.com/tc39/proposals/blob/master/finished-proposals.md)

## やりかた

- [x] 検討リストから対応するべきかを決める
- [x] 対応するものは別途Issue化する
- [x] 対応する
- [x] すべて対応したら `book.js` を更新
- [x] リリースノートを公開する

## スケジュール

- 4月-5月: 検討する
- 5-6月: 実装
- 6月: ES2023の正式リリースと合わせて公開
  - 大体6月後半に [News - Ecma International](https://www.ecma-international.org/news/) でリリースされる 
  - スナップショットは[Release ES2023 Candidate April 2023 · tc39/ecma262](https://github.com/tc39/ecma262/releases/tag/es2023-candidate-2023-04)
 
## 検討リスト

- [x] [tc39/proposal-array-find-from-last: Proposal for Array.prototype.findLast and Array.prototype.findLastIndex.](https://github.com/tc39/proposal-array-find-from-last)
- [ ] [tc39/proposal-hashbang: #! for JS](https://github.com/tc39/proposal-hashbang)
- [x] [tc39/proposal-symbols-as-weakmap-keys: Permit Symbols as keys in WeakMaps, entries in WeakSets and WeakRefs, and registered in FinalizationRegistries](https://github.com/tc39/proposal-symbols-as-weakmap-keys)
- [x] [tc39/proposal-change-array-by-copy: Provides additional methods on Array.prototype and TypedArray.prototype to enable changes on the array by returning a new copy of it with the change.](https://github.com/tc39/proposal-change-array-by-copy)

## 過去

- #1337 
- #1220 
- #1145

**Comment by azu** [comment]
## proposal-array-find-from-last

lastIndexOfがあるので、findLastIndexの対応を追加するのが自然そう

https://jsprimer.net/basic/array/#indexof 最後に追加する感じかな。

**Comment by azu** [comment]
## Hashbang Grammar

Node CLIのユースケースはCLIの配布までやってないので、hashbangが出てこない。

https://jsprimer.net/basic/comments/　に1行コメントの亜種として足すのはありそうだけど、あんまり強い理由ないかも。

HTML-likeコメントみたいに可能なら追加するぐらいかな。
あんまり増やしても意味はないので、何か面白くなるような感じなら足すイメージ

**Comment by azu** [comment]
## Symbol as a Key

仕組み的には結構面白いことになってる。

- Symbol()
- Symbol.for()

に意味的な違いが結構出てる。

対応的には、weakの話でキーに指定できるものへsymbolが追加されたことだけど、
キーに指定できるものを書いてはない?

- https://jsprimer.net/basic/map-and-set/

> また、弱い参照で値を持つ特性上、WeakSetの値として使えるのは参照型のオブジェクトだけです

Setのここだけ修正が入りそう

**Comment by azu** [comment]
## Change Array by copy

これは対応しないといけない。
詳細はIssueを切って考える

**Comment by azu** [comment]
ES2023がリリースされるのは 27.06.2023 - 28.06.2023の予定
Meeting calendar - Ecma International
https://www.ecma-international.org/about-ecma/meeting-calendar/

Firefoxが対応してるかどうか

- [x] hashbag

```js
#!test
```

- [x] #1665 

```js
const array = [{ value: 1 }, { value: 2 }, { value: 3 }, { value: 4 }];
array.findLastIndex(n => n.value % 2 === 1); // 2
array.findLastIndex(n => n.value === 42); // -1
```

- [ ] #1666 

```js
const map = new Map();
const s = Symbol("desc");
map.set(s, {})
map.get(s);
```

- [ ] Change Array by copy

```js
const sequence = [1, 2, 3];
sequence.toReversed(); // => [3, 2, 1]
sequence; // => [1, 2, 3]

const outOfOrder = new Uint8Array([3, 1, 2]);
outOfOrder.toSorted(); // => Uint8Array [1, 2, 3]
outOfOrder; // => Uint8Array [3, 1, 2]

const correctionNeeded = [1, 1, 3];
correctionNeeded.with(1, 2); // => [1, 2, 3]
correctionNeeded; // => [1, 1, 3]

**Comment by azu** [comment]
https://www.ecma-international.org/news/ecma-international-approves-new-standards-at-the-125th-general-assembly-27-june-2023/
https://github.com/tc39/ecma262/releases/tag/es2023
リリース

**Comment by azu** [comment]
[Hashbang Grammar](https://github.com/tc39/proposal-hashbang)
以外は対応が完了。

[コメント · JavaScript Primer #jsprimer](https://jsprimer.net/basic/comments/)に足すかはなんか微妙。
とりあえずIssue化して対応したい人がいたら対応するぐらいでいいかな。

あとはリリースノートとかを書く

**Comment by azu** [comment]
- リリースノートのドラフト: https://github.com/asciidwango/js-primer/releases/tag/untagged-2a67411a24429ba5b873
- リリース後に、 https://jsprimer.net/intro/#changelog へ追加する

**Comment by azu** [comment]
- [ ] リリースノートにライセンスの変更についてを追加する #1690 
- [ ] 水曜ぐらいにリリース

**Comment by azu** [comment]
https://github.com/asciidwango/js-primer/releases/tag/v5.0.0
https://efcl.info/2023/08/31/jsprimer-v5/
https://twitter.com/azu_re/status/1697053666006667604

リリース！！
