### ISSUE TITLE
Open Source Collective

### ISSUE THREAD

**Issue by azu** [asciidwango/js-primer#1674]
[Open Collective](https://opencollective.com/)の[Open Source Collective](https://www.oscollective.org/)を利用するために進めてるので、それを管理するIssue。

- ページ: https://opencollective.com/jsprimer

## 目的

jsprimerというプロジェクトに対して支援できる仕組みを作り、Contributorがそれを受け取れるような仕組みを作りたい。
それによって、jsprimerが更新し続けられる状態を作り、よりContributorが増える状態にしたい

## 考えること

- [x] どういうプラン(寄付に対するリターン)があると支援しやすいか
  - Open Source CollectiveはUSの法人なのでUSD固定になっている
- [ ] Open Collectiveを使ったContributorのworkflow
  - これ自体は来年ぐらいで。まだ何もないから後でいい 

## TODO

- [x] [Open Collective](https://opencollective.com/)のCollective作成
- [x] [Open Source Collective](https://www.oscollective.org/)へ申請
- [x] [Open Source Collective](https://www.oscollective.org/)の確認
- [ ] サイト上からのリンクの追加など

**Comment by azu** [comment]
申請が通った

**Comment by azu** [comment]
https://opencollective.com/jsprimer
ページを作成した

**Comment by azu** [comment]
@lacolaco Open Collectiveのアカウントって持ってます?
Inviteしておきたいです

**Comment by lacolaco** [comment]
@azu これです。https://opencollective.com/lacolaco

**Comment by azu** [comment]
Invited

**Comment by azu** [comment]
- [ ] Open Source Collectiveで請求をするときは、何に対するものなのかとか結構ちゃんと明記する必要があるので、そのフローを考える
- [Invoice and Reimbursements - Open Source Collective](https://docs.oscollective.org/how-it-works/basics/invoice-and-reimbursement-examples)
