### ISSUE TITLE
utils.parseArgsの利用法を追記

### ISSUE THREAD

**Issue by yusuke-omae** [asciidwango/js-primer#1698]
## 該当ページ

- [x] https://jsprimer.net/use-case/nodecli/argument-parse/

## リクエスト/提案内容

当ページではnpmパッケージを利用するチュートリアルとして`commander`パッケージを利用しています。
ただしnode.js v20.9.0(LTS)では`import { parseArgs } from 'node:utils'`を用いることでnpmパッケージ非依存で当該処理を解決できます。
https://nodejs.org/dist/latest-v20.x/docs/api/util.html#utilparseargsconfig
この関数に関して下記のいずれかの対応があった方がいいと思います。

- あえて無視していることを記述
- コラムとして現状のnode.jsには当該関数があることを明記
- `commander`パッケージから置き換える（npmパッケージ使用のチュートリアルを別ページに書く必要がでる）

以上検討していただけるでしょうか。

## TODO

- [x] #1718 に依存している
- [ ] `mpm init` の話を[コマンドライン引数を処理する](https://jsprimer.net/use-case/nodecli/argument-parse/) → [ECMAScriptモジュールを使う](https://jsprimer.net/use-case/nodecli/argument-parse/#esmodule)の中に移動する
- [ ] [commanderパッケージをインストールする](https://jsprimer.net/use-case/nodecli/argument-parse/#install-commander)を削除
- [ ] `node:*` やコアモジュールの説明を [ファイルを読み込む](https://jsprimer.net/use-case/nodecli/read-file/) →　[ECMAScriptモジュールを使う](https://jsprimer.net/use-case/nodecli/argument-parse/#esmodule)へ移動する
- [ ] `commander` を `util.parseArgs` に変更する 
  - https://jsprimer.net/use-case/nodecli/md-to-html/ もparseArgsに変更

Ref https://github.com/asciidwango/js-primer/issues/1698#issuecomment-1935345984

**Comment by azu** [comment]
https://github.com/asciidwango/js-primer/blob/50e3b7b86b75a48ea9d56f297ec21247914c2247/meetings/2022-08-18/README.md?plain=1#L46

まだ入れてなかったのは、以前はexperimentalでの実装だったからですね。
`node:test`も含めて、Node CLIの章を書き直すのが良いと思います。

- [Util | Node.js v21.4.0 Documentation](https://nodejs.org/api/util.html#utilparseargsconfig)
- [Test runner | Node.js v21.4.0 Documentation](https://nodejs.org/api/test.html)

一応外部モジュールを扱うユースケースではあるので、`npm install`が必要になるのが`marked`まで後ろにずれてしまうのが気になるところですかね。

**Comment by azu** [comment]
[Node.jsでCLIアプリ · JavaScript Primer #jsprimer](https://jsprimer.net/use-case/nodecli/)でcommanderを使わなくなった場合、markedの部分で初めてnpm installとpackage-lockが登場するようになるはず。
ただし、type=moduleを入れるので、npm initは必ず最初にいる

この場合に、節を入れ替えることも一応できるけど、流れ自体は別に変えなくても良さそう。

- util→fs→marked
  - 流れは現状のまま
- fs→util→marked
  - fsを先にくる

[コマンドライン引数を処理する · JavaScript Primer #jsprimer](https://jsprimer.net/use-case/nodecli/argument-parse/)からnpm install周りの話を[MarkdownをHTMLに変換する · JavaScript Primer #jsprimer](https://jsprimer.net/use-case/nodecli/md-to-html/)に移して、それぞれのボリュームが大きく崩れないかはちょっと気になる。
(段々とボリュームが増えていくぐらいの構造が読みやすいはず)

**Comment by azu** [comment]
このissueのやることは二つに分けて進めるのがよさそう

## commander をやめる
https://jsprimer.net/use-case/nodecli/argument-parse/
から

- mpm initとcommonjsの件をhttps://jsprimer.net/use-case/nodecli/helloworld/ に移動する
  - プロジェクトのセットアップの話としてnpm initする
- commanderをparseArgvに変更する
- https://jsprimer.net/use-case/nodecli/md-to-html/ もparseArgvに変更


バランスがおかしくないかはみる必要がありそう。

## mocha を node:test に変更する

https://jsprimer.net/use-case/nodecli/refactor-and-unittest/ をnode:testにする

懸念点としてはdevDependenciesの話がなくなってしまうこと。

--

とりあえずこの二つのフェーズに作業分けて進めるのがよさそう。

あとmarkedのアップデートもあるので3つissueに分けて進める。来週のjsprimer weekの記事で募ってみる

cc @lacolaco

**Comment by lacolaco** [comment]
ありがとうございます！

**Comment by azu** [comment]
@yossydev さん と @jp-knj さんに担当してもらう
