### ISSUE TITLE
[meta] JavaScriptの基本文法

### ISSUE THREAD

**Issue by azu** [asciidwango/js-primer#17]
#8 で基本文法の章を書くことになったので、基本文法に関するメタIssueです。

Issueの目次のような感じ かつ 基本文法の章にあったほうがいいものをメモって置くIssueです。
- [x] JavaScriptの導入  #18
  - JavaScriptって何?とこの章の目的
- [x] JavaScriptの概要 #87 
- [x] コメント #16 
- [ ] 変数宣言 #15 
- [x] 関数宣言 #20 
- [x] 値の評価方法、コンソールへ出力 #14 
- [x] リテラル/値/Primitive #27 
- [ ] 式(Expression)と文(Statement) #70 
- [x] 制御構文 if/switch/block/space #31 
- [x] ループ: for/for in/for of/while/do while #68 
- [x] 演算子 #32 
- [x] 型変換 #53
- [ ] エラー
- [ ] try...catch文 #93
- ビルトインオブジェクト
  - Object  #126
  - String 
  - Math/Number #100 
  - Array #49 
- [ ] 関数 #112 
  - [x] 関数宣言、関数式、Arrow Function #20 #119
  - [ ] スコープ/クロージャー #277 
- [ ] class #39 
- [ ] Promise #94 

この辺でもうある程度書ける

---

その他の書く候補
- 基礎文法
  - #112 関数のまとめ
  - Destructuring
  - 関数/Arrow Function
  - Spread Operator
  - Error/Throw
  - クラス
  - 正規表現
  - Generator/Iterable/Iterator
- ビルトインオブジェクト
  - JSON
  - Date
  - Map/WeakMap
  - Set/WeakSet
  - Symbol
  - Promise
- Note
  - ECMAScript策定プロセス
  - Reflect API - Proxyとセット
  - Proxy - むずかしそう
  - Unicode - サロゲートペアとか
  - Intl - やるか微妙

**Comment by azu** [comment]
制御構文と演算子はどっちが先だろ?
先に、制御構文は数字だけで進めるのが分かりやすい気もする。
何も説明せずに+ = > < 演算子を使うけど、演算子はプログラミング言語で大体共通だから読めなくはないはず。

**Comment by azu** [comment]
型変換はそれぞれのConstructorを使うので解説順に悩む。
Object, Number, String, ... ごとに説明をするべきなのかなー

**Comment by azu** [comment]
[The Most In-Depth Yet Understandable ES6 Destructuring Tutorial (complete with Assembled Avengers) | Untangled](http://untangled.io/in-depth-es6-destructuring-with-assembled-avengers/ "The Most In-Depth Yet Understandable ES6 Destructuring Tutorial (complete with Assembled Avengers) | Untangled")

Destructuring ってものすごい立ち位置が分かりにくい。
shorthandというジャンルな気はするけど

**Comment by azu** [comment]
ビルトインオブジェクトの話についてどうするか考えないとちょっとダメだなー
どうしてもただのリファレンスになりそうな気がしているから、ビルトインオブジェクトごとにテーマを設けて、それにそって説明していくという話にしないと収集がつかない感じ。

例えば、 NumberとMath #100 なら浮動小数点数 `0.1 + 0.2 === 0.3` はなぜ falseなのかを解いて見ましょうとか。

なんでもかんでもArrayを返す関数を作っていくプログラミングスタイルはなぜ起きるのでしょうか?
(こういうの実際どうしてそうした方が安全な感じになるのかって研究あるのかな? モナドとかそういう数学的な話になっていくのかな)
常にオブジェクトを返すプログラミングスタイルと配列を返すスタイルは何が違うのか?とか(0上の値の集合という点では同じだけど、オブジェクトの場合は"次"の定義がないからというのが大きそう)
"次"が決まっているのはiterableが概念そのもので、ArrayもIterableであるとかなんとか

オブジェクトは、JavaScriptがオブジェクトで作られているという話になるのかな。

**Comment by azu** [comment]
後は、API一覧を出さなくてもAPI一覧がつかめるというか、調べられる道筋を示せるのがただしい感じはするけど、安易なAPI一覧は楽すぎるのがなー

**Comment by azu** [comment]
[JavaScript文法(1) 学習環境の構築と基本的な書き方 - Qiita](http://qiita.com/azk0305/items/a13d494178d83fc8f2bc "JavaScript文法(1) 学習環境の構築と基本的な書き方 - Qiita")

**Comment by azu** [comment]
- ビルトインオブジェクト
    - Object  #126
    - 関数 #112 
-  prototype/ブロックスコープ/クロージャー #24 
-  class #39 

個人的にこれらが一つのセットであるような感じがするので、これを一つのまとまりとして考えてアウトラインを出す必要がありそう。

[関数で知っておきたいこと](https://github.com/asciidwango/js-primer/issues/112#issuecomment-239627208)で一通り要素を書いてみたけど、関係することが多い感じ。
`this` をどこで扱うかがイマイチ決まらない。
個人的にはclassであるとも思うけど、オブジェクトのメソッドでも使えるから悩ましい感じ。
Learning JavaScriptでは、関数のメソッドの話として出してた(classはその後)

**Comment by azu** [comment]
`new プリミティブ` を避けるためにSymbolはnewできないって面白いなー。
+ Symbol()がエラーなのも同じような意図なんだろなー

- [Why ES6 introduced classes yet `Symbol` not to be used with `new`?](https://esdiscuss.org/topic/why-es6-introduced-classes-yet-symbol-not-to-be-used-with-new "Why ES6 introduced classes yet `Symbol` not to be used with `new`?")

**Comment by azu** [comment]
- JavaScriptの導入  #18
	- JavaScriptって何?とこの章の目的
- JavaScriptの概要 #87 
- コメント #16 
- 変数宣言 #15 
- 関数宣言 #20 
- 値の評価方法、コンソールへ出力 #14 
- リテラル/値/Primitive #27 
- 式(Expression)と文(Statement) #70 
- 制御構文 if/switch/block/space #31 
- ループ: for/for in/for of/while/do while #68 
- 演算子 #32 
- 型変換 #53

ここまでで、具体的なAPIは知らないけどコードは書けるようになる気がする。
ここまでの振り返りも兼ねて演習問題的なものがあるといいのかもしれない。

一つ思いついたのは、i18n APIを使って
指定した言語で、入力した金額を表示に消費税を加えるという感じの問題。

言語の一覧から探索(loop)、数字のパース(型変換)、存在の有無(制御構文)、演算子(加算)
みたいな感じにできていいかなとか思った。

けど、loopのところがi18n APIだと特にない気がする。

**Comment by azu** [comment]
税込みの金額を出すサンプル
http://jsbin.com/fuwovevaji/edit?js,console

やっぱりループを絡ませることができない…

**Comment by azu** [comment]
[meta] JavaScriptの基本文法 #17
