### ISSUE TITLE
ECMAScript 2024の対応

### ISSUE THREAD

**Issue by azu** [asciidwango/js-primer#1706]
ES2024対応のメタIssueです

- [proposals/finished-proposals.md at main · tc39/proposals](https://github.com/tc39/proposals/blob/main/finished-proposals.md)

## やりかた

- [x] [JavaScript Primer - Open Collective](https://opencollective.com/jsprimer)でのアナウンス
- [x] 検討リストから対応するべきかを決める
- [x] 対応するものは別途Issue化する
- [x] 対応する
- [x] すべて対応したら `book.js` を更新
- [ ] リリースノートを公開する

## スケジュール

- 1月: TC39で最終的にFeature Freezeされる
- 1-6月: 検討、実装
- 6月: ES2023の正式リリースと合わせて公開
  - 大体6月後半に [News - Ecma International](https://www.ecma-international.org/news/) でリリースされる 

## 検討リスト

検討対象のリスト

- [x] [tc39/proposal-is-usv-string: a proposal for a method to determine if a String is welll-formed Unicode](https://github.com/tc39/proposal-is-usv-string)
- [x] [tc39/proposal-atomics-wait-async: "asynchronous atomic wait" for ECMAScript](https://github.com/tc39/proposal-atomics-wait-async)
- [x] [tc39/proposal-regexp-v-flag: UTS18 set notation in regular expressions](https://github.com/tc39/proposal-regexp-v-flag)
- [x] [tc39/proposal-resizablearraybuffer: Proposal for resizable array buffers](https://github.com/tc39/proposal-resizablearraybuffer)
- [x] [tc39/proposal-array-grouping: A proposal to make grouping of array items easier](https://github.com/tc39/proposal-array-grouping)
- [x] [tc39/proposal-promise-with-resolvers](https://github.com/tc39/proposal-promise-with-resolvers)

## 対応リスト

実際に対応するリスト

- [x] #1716 
- [x] https://github.com/asciidwango/js-primer/issues/1715

## 過去

- #1658 
- #1337 
- #1220 
- #1145

**Comment by azu** [comment]
合わせて考えたいこと

- #1674
- #1694 
- #1698

**Comment by azu** [comment]
## First Impression

- [tc39/proposal-is-usv-string: a proposal for a method to determine if a String is welll-formed Unicode](https://github.com/tc39/proposal-is-usv-string)

[サロゲートペア](https://jsprimer.net/basic/string-unicode/#surrogate-pair)で判定方法として触れる可能性がある。

- [tc39/proposal-atomics-wait-async: "asynchronous atomic wait" for ECMAScript](https://github.com/tc39/proposal-atomics-wait-async)

Atomicsは触れてないので特に触れない

- [tc39/proposal-regexp-v-flag: UTS18 set notation in regular expressions](https://github.com/tc39/proposal-regexp-v-flag)

[文字列とUnicode · JavaScript Primer #jsprimer](https://jsprimer.net/basic/string-unicode/)で触れる可能性はあるがちょっとAdvancedな感じがする

- [tc39/proposal-resizablearraybuffer: Proposal for resizable array buffers](https://github.com/tc39/proposal-resizablearraybuffer)
- [tc39/proposal-arraybuffer-transfer: Proposal to add ArrayBuffer.prototype.transfer](https://github.com/tc39/proposal-arraybuffer-transfer)

ArrayBufferの詳細は触れてないので触れない。

- [tc39/proposal-array-grouping: A proposal to make grouping of array items easier](https://github.com/tc39/proposal-array-grouping)

[配列 · JavaScript Primer #jsprimer](https://jsprimer.net/basic/array/) で検討する

- [tc39/proposal-promise-with-resolvers](https://github.com/tc39/proposal-promise-with-resolvers)

[非同期処理:Promise/Async Function · JavaScript Primer #jsprimer](https://jsprimer.net/basic/async/)でDefferredについては触れてないので触れないかもしれない。

**Comment by azu** [comment]
## [Well-Formed Unicode Strings](https://github.com/tc39/proposal-is-usv-string)

孤立したサロゲートペアを発見するメソッド。
```js
encodeURIComponent("\uD800")
```
のような孤立したサロゲートペアを受け取ると例外を投げる文字列の判定に利用できる。

[サロゲートペア(https://jsprimer.net/basic/string-unicode/#surrogate-pair)では、特に孤立したサロゲートペアについては触れていない。
そのため、追加するかはちょっと微妙。コラム的に書くのはありかもしれないぐらいな印象

**Comment by azu** [comment]
## [tc39/proposal-atomics-wait-async: &quot;asynchronous atomic wait&quot; for ECMAScript](https://github.com/tc39/proposal-atomics-wait-async)

`Atomics.waitAsync`
`Atomics`自体が登場していないため、特に触れない

### 結論

対応しない

**Comment by azu** [comment]
## [tc39/proposal-regexp-v-flag: UTS18 set notation in regular expressions](https://github.com/tc39/proposal-regexp-v-flag)

特にフラグを網羅してるわけではないので、触れなくても問題なさそう。
フラグの一覧だけを出すというのはありかもしれないが、現状はそのパターンがないので触れない

### 結論

対応しない

**Comment by azu** [comment]
## ArrayBuffer

- [tc39/proposal-resizablearraybuffer: Proposal for resizable array buffers](https://github.com/tc39/proposal-resizablearraybuffer)
- [tc39/proposal-arraybuffer-transfer: Proposal to add ArrayBuffer.prototype.transfer](https://github.com/tc39/proposal-arraybuffer-transfer)

ArrayBuffer自体を扱っていないので対応しない

### 結論

対応しない

**Comment by azu** [comment]
## [tc39/proposal-array-grouping: A proposal to make grouping of array items easier](https://github.com/tc39/proposal-array-grouping)

Web互換性のために`Object.groupBy`になった。
`Map.groupBy(array, fn)`もある。

グループ化は頻出ではあるので含めるのは妥当そうだけど、配置が難しい

- `Array.prototype.group` → `Object.groupBy(array, cb)`
- `Array.prototype.groupToMap` → `Map.groupBy(array, cb)` 

という経緯。
どちらも配列を引数として受け取るようになってるので、配列関係。

データの変換的に見れば

- `Object.groupBy` は 配列をオブジェクトにするメソッド
- `Map.groupBy` は配列をMapにするメソッド

として捉えられる。

`Object.groupBy`は、 配列 to objectなので、[Array.prototype.reduce ](https://jsprimer.net/basic/array/#array-reduce)の近くにあるのが良さそう。
`Map.groupBy`は、[Map/Set](https://jsprimer.net/basic/map-and-set/)にあるのが良さそう。
`Map.groupBy`はちょっと必要かは怪しい。

## 結論

- `Object.groupBy`: 配列の章に追加する
- `Map.groupBy` は Map/Setの章に追加する?

**Comment by azu** [comment]
## [tc39/proposal-promise-with-resolvers](https://github.com/tc39/proposal-promise-with-resolvers)

[Promise.withResolvers によるイベントの Promise 化 | blog.jxck.io](https://blog.jxck.io/entries/2024-02-10/promise.withresolvers.html)
Defferredパターンが必要なのは、イベントの付与とPromiseを組み合わせる時。
書籍では特に出てこない。

[Ajax通信 · JavaScript Primer #jsprimer](https://jsprimer.net/use-case/ajaxapp/)はclickが最初に決まっているので、クリックしたタイミングで付与するわけじゃない。XHRならありえたけど。

少し発展的なパターンなので、この本だと不要そう。

## 結論

対応しない。

- https://github.com/azu/promises-book/issues/366

**Comment by azu** [comment]
https://github.com/tc39/ecma262/releases/tag/es2024-candidate-2024-02
ES2024 RCがリリースされた
