### ISSUE TITLE
TODOアプリ

### ISSUE THREAD

**Issue by azu** [asciidwango/js-primer#4]
TODOアプリをユースケースとして作ってみようと言う話があったので。
## TODO

- [x] Todoアプリにタイトル変更機能はいらないことする
- [x] Todoアプリに最低限のスタイルを当てる #432 
- [x] クラスのEventEmitterをTodoアプリの方に移動する
    - <https://github.com/asciidwango/js-primer/issues/424>
- [x] Todoアプリのソースは最終形と断片を読み込んで書く
    - 分割するラインを決めていく
- [x] ES moduleのネットワークエラーについてを書く
- [ ] <del>Todoアプリにフィルターをいれる</del>
   - 独立して追加できるので「やってみよう」に落とすかも
   - ボリューム的に最初は落とす
- [x] セクションまとめはチェックボックスへ
- [x] スクリーンショットを取り直す
- [x] ローカルサーバの立て方の変更 #462 
- [x] イベントの用語統一   #455 
- [ ] タイトルを動詞(目的)に変更

## アウトライン

- https://github.com/asciidwango/js-primer/blob/master/source/use-case/todoapp/OUTLINE.md
## セクションまとめのチェックボックス

- セクションごとでやったことをチェックボックスにする

**Comment by azu** [comment]
Web+DB vol92にTODOのサンプル乗ってたけど、ひたすら解説難しそうだなという感じがした。

**Comment by azu** [comment]
構成要素を追記

**Comment by azu** [comment]
[Amazon.co.jp: いまから始めるWebフロントエンド開発 電子書籍: 松田 承一, 柴田 和祈: Kindleストア](https://www.amazon.co.jp/dp/B01IEKIW7U/ "Amazon.co.jp: いまから始めるWebフロントエンド開発 電子書籍: 松田 承一, 柴田 和祈: Kindleストア")
ReactとかReduxっぽいけどTodoの話

**Comment by azu** [comment]
[レトロエンジニアのための近代Webフロントエンド事情 - Qiita](http://qiita.com/uctakeoff/items/ce8da368d020273c6064#fnref5 "レトロエンジニアのための近代Webフロントエンド事情 - Qiita")
面白かった。

ツール実際に使うならどうするか悩むなー。
実在するツールを使うべきなのか それとも `js-primer-transpile` とか `js-primer-bundler` みたいなツールをでっちあげてやるべきなのかというのがある。
ツール自体の軽い話はあってもいいけど、ツールの使い方を学ぶのは本質的じゃないしなー

**Comment by azu** [comment]
https://paulirish.github.io/es-modules-todomvc/
ES6モジュールでのTODO実装

**Comment by azu** [comment]
クラスとモジュールが１つのテーマ
オブジェクト指向的なアプリケーションの作り方ユースケース。

**Comment by azu** [comment]
[【感想】いまから始めるWebフロントエンド開発 - Rのつく財団入り口](http://iwasiman.hatenablog.com/entry/2018/03/19/200000 "【感想】いまから始めるWebフロントエンド開発 - Rのつく財団入り口")
todoアプリ題材

**Comment by azu** [comment]
`.js` を付けないとエラーがでますというエラー例を表示す。

**Comment by azu** [comment]
- [Todoアプリ](./use-case/todoapp/README.md)
    - [エントリポイント](./use-case/todoapp/entrypoint/README.md)
    - [アプリの構成要素](./use-case/todoapp/app-structure/README.md)
    - [フォームとイベント](./use-case/todoapp/form-event/README.md)
　 - EventEmitterとモデル
     - Todoアイテムの追加
     - Todoアイテムの更新と削除

ちょっと長いかな?

**Comment by azu** [comment]
フォームとイベントのところを最初からEventEmitterでやればまあもっと短くなるんだろうけど、イベント駆動なれてない人がやるにはいきなりは抽象的な感じがした。
できるだけ、`...省略...` を行わないデザインでやってて、モジュールをちょこっと作ってApp.jsを変更をやってる感じ。
そろそろApp.jsがでかくなってくるので少し無理が出てくるかも

**Comment by azu** [comment]
[Introduction for Browser Side MVC](https://www.slideshare.net/tricknotes/introduction-for-browser-side-mvc)
モデルの話について

**Comment by azu** [comment]
各セクションのタイトルを 〜する みたいな感じに変更する。
検索的にももうちょっとタイトル単体でわかるようにした方がよかった。

**Comment by azu** [comment]
https://asciidwango.github.io/js-primer/use-case/todoapp/
Todoアプリの章はひとまず書き終わり。
途中のミーティング  #454 でイベントの用語  #455 やローカルサーバの話  #462 とかの変更があったので、前半と後半がまだ整ってない。
その辺の統一したら、これを閉じる。

今のところのブロッカーは #462 のローカルサーバとは?みたいな話。
2章の序章 #267  を参照したいけど、まだそこがない。

**Comment by azu** [comment]
あと、Todoの数の表示の部分 なんかイマイチ。
モデルの説明には役立つけど、後半はただ邪魔になってるだけから、モデルの説明はアプリじゃない例でやるとかして、Todoの数表示自体を取り除くかもしれない

**Comment by azu** [comment]
- [ ] ローカルサーバの変更を取り入れる

**Comment by azu** [comment]
次のタスクをしたら閉じる。

- [ ] [`npx @js-primer/local-server` · Issue #462 · asciidwango/js-primer](https://github.com/asciidwango/js-primer/issues/462 "`npx @js-primer/local-server` · Issue #462 · asciidwango/js-primer")
- [ ]  [npm の --global flagについての説明 · Issue #574 · asciidwango/js-primer](https://github.com/asciidwango/js-primer/issues/574 "npm の --global flagについての説明 · Issue #574 · asciidwango/js-primer")
- [ ] [Todoアプリのリファクタリング · Issue #606 · asciidwango/js-primer](https://github.com/asciidwango/js-primer/issues/606 "Todoアプリのリファクタリング · Issue #606 · asciidwango/js-primer")

TODOアプリはmount,unmountまで完成してない感じなので、
課題として、そこを別のIssueにして、後は自分でやってみよう + 完成形を作っておくかな
