### ISSUE TITLE
PWA化について

### ISSUE THREAD

**Issue by nd-02110114** [asciidwango/js-primer#431]
## PWAの導入
Lighthouseの結果、PWAのスコアが低かったので修正してみました #430 
個人的なモチベーションでやってみただけなので、
もし特にモチベーションないとかであればこのIssueはCloseしてもらって大丈夫です

### TODO
- [x] Service Workerの登録
- [x]  Web manifest.jsonの追加

### Not TODO
まだまだ修正点あると思います

- [x] Web manifest.jsonの修正
  - [x] Iconの入れ替え (PRでは仮のものを当てている)
  - [x] background_color, theme_colorの入れ替え (適当な色を当てている)

- [x] Service Workerの登録
  - [ ] 細かいCacheの作り方のルールを決める 
 
 ### Result
|          | 
|---------------------------|
| 修正後 |
| <img width="600" alt="2018-03-23 0 04 29" src="https://user-images.githubusercontent.com/17228098/37806913-f5396898-2e85-11e8-9c09-1ef4d008f5b9.png"> |
| 修正前 |
| <img width="600" alt="2018-03-23 0 06 14" src="https://user-images.githubusercontent.com/17228098/37806924-fc513bec-2e85-11e8-912d-845a6725221a.png"> |

**Comment by azu** [comment]
Google AnalyticsのSW対応なども考えると[Workbox](https://github.com/GoogleChrome/workbox "Workbox")を使ったほうが楽かもしれないですね。

**Comment by nd-02110114** [comment]
コメントありがとうございます。
恥ずかしながら、聞いたことのなかったツールなので少し調べてみたいと思います 🙇

**Comment by azu** [comment]
正規表現でキャッシュするパターンを指定したり、Google Analyticsの対応だったり(まあGoogleが作ってるので)などSWでよくあるキャッシュのパターンをフレームワーク化したものですね。
キャッシュするのは多分GItBookが作成したファイルだけで済むはず(外部リソースはしなくてもいいはず?)なので、ビルドプロセス(`npm run build`)にWorkboxでsw.jsを作る処理を追加すると多分キャッシュはできる気はします。

GitBookのプラグインで似たようなことするのありそうだなと思いましたが、[gitbook-plugin-offline - npm](https://www.npmjs.com/package/gitbook-plugin-offline "gitbook-plugin-offline - npm")はWorkboxの前身の sw-precache 使って似たような事やってるみたいですね。

**Comment by nd-02110114** [comment]
おお、💯になったのは良かったです！
Issueは、閉じて大丈夫なので、僕の方で閉じておきます。レビューありがとうございました🙇🏻

**Comment by azu** [comment]
@nd-02110114 こちらこそありがとうございます。

**Comment by azu** [comment]
[js-primer(JavaScript入門本)がオフラインで読めるようになりました | Web Scratch](https://efcl.info/2018/05/25/js-primer-offline/)
記事を書きました

**Comment by nd-02110114** [comment]
ありがとうございます！
js-primerが盛り上がって、もっとcontributer増えると良いですね 👍
