### ISSUE TITLE
用語: イベントを~する

### ISSUE THREAD

**Issue by azu** [asciidwango/js-primer#455]
イベントを

- 発火
- 発行
- 実行

どれかに統一するように辞書に入れておきたい。
元の言葉から別々だから厳密な統一はできないんだろうけど。
DOM APIのイベントとかそういうコンテキストでは統一できそうな気がする。

DOM APIは `dispatchEvent`、Node.jsは `emit` 。
ただDOM APIの方と、自作のEventEmitterしかでてこないので、そこの間の用語を合わせたい。

今は "発火" が使われてる。

## 結論

#454 #492 で議論された。

- イベントをディスパッチする
- イベントをリッスンする
- イベントが発生した
- イベントリスナー (イベントハンドラーではなくリスナー)
  - リスナー関数

に統一することにした

## Tasks 

- [ ] イベント用語を統一 #488 
- [ ] イベントハンドラは イベントリスナーに 統一する  #488
- [ ] イベントリスナーは イベントハンドラーともよばれることがありますが、この書籍では区別しませんと入れる
  - https://asciidwango.github.io/js-primer/basic/map-and-set/#weakmap
- [ ] リスナーにprh統一する辞書を入れる

**Comment by azu** [comment]
https://twitter.com/azu_re/status/994762945312669696

**Comment by azu** [comment]
- イベントをディスパッチする
- イベントをリッスンする

に統一することにした

#454

**Comment by azu** [comment]
イベントハンドラーとイベントリスナーの区別どうするか。
書いててもよくわからなくなってきた

**Comment by azu** [comment]
イベントハンドラーとイベントリスナーの区別はしないという宣言をした方がいい気がするな。
違いが感覚的すぎる…

**Comment by azu** [comment]
[早わかり イベントモデル - 檜山正幸のキマイラ飼育記](http://d.hatena.ne.jp/m-hiyama/20071206/1196905196)

**Comment by azu** [comment]
- [ ] イベントリスナーに統一する
- [ ] イベントリスナー = イベントハンドラー として扱うことを宣言する

**Comment by azu** [comment]
[JavaScript - イベントハンドラとイベントリスナの用語の使い分けを教えてください(4024)｜teratail](https://teratail.com/questions/4024)
質問がある程度に疑問を持つ人はいるけど、まあ調べればなんとなくわかるからいいか
