### ISSUE TITLE
[meta] 関数と宣言/非推奨の章: リファクタリング

### ISSUE THREAD

**Issue by azu** [asciidwango/js-primer#590]
`arguments` の問題は次の3つの要素を解決すれば、非推奨の機能の章が消せる
(非推奨の章は #142 で消すことになっている)

- [ ] https://jsprimer.net/basic/bad-parts/ を削除する https://github.com/asciidwango/js-primer/issues/595
  - 関数と宣言で arguments のデメリットを扱うため
- [ ] argmentsをrest parameterで代替えできることを https://jsprimer.net/basic/function-declaration/ で明示する
  - ↑の説明
- [ ] デフォルト引数についても"演算子"から"関数と宣言"に移動する
  - デフォルト引数を"関数と宣言"の引数周りの説明で扱う
- [ ] [関数と宣言: 引数の個数について · Issue #588 · asciidwango/js-primer](https://github.com/asciidwango/js-primer/issues/588)
  - 引数周りの説明を追加する
- [ ] 関数宣言と関数式の違いについてを追記 https://github.com/asciidwango/js-primer/issues/284
  - 補足

## Issue

- https://github.com/asciidwango/js-primer/issues/284
- https://github.com/asciidwango/js-primer/issues/274
- https://github.com/asciidwango/js-primer/issues/588
- https://github.com/asciidwango/js-primer/issues/595

**Comment by azu** [comment]
https://github.com/asciidwango/js-primer/blob/master/source/basic/function-declaration/OUTLINE.md
このアウトラインになるように関数と宣言を書き直す

**Comment by azu** [comment]
- [ ] デフォルト引数についても"演算子"から"関数と宣言"に移動する
