### ISSUE TITLE
モジュールの章を移動する

### ISSUE THREAD

**Issue by azu** [asciidwango/js-primer#644]
モジュールの章の目的はモジュールの概念をわかってもらう + Todoからリファレンスする甩

章の順番を並び替える。

次のような章の並びに変更して、辻褄があってるかを確認する

    Math
    Module
    ECMAScript

## Tasks

- [x] モジュールの章を移動
- [x] タイトルをモジュールから"ES Module"?に変更
- [x] モジュールからCommonJSを移動
- [ ] モジュールからbundlerを移動
- [x] モジュールのnamed,defaultの順番変更 https://github.com/asciidwango/js-primer/issues/860#issuecomment-507208656

**Comment by azu** [comment]
#803 で話し合った結果、Mathの次、ECMAScriptの前に移動することになった

**Comment by azu** [comment]
結論

    モジュールの章を https://jsprimer.net/basic/math/ の後にする
    モジュールの概念を知る、具体的はユースケースで
        https://jsprimer.net/use-case/module/#run-es-modules (ここサーバないと動かないので、開発環境の準備を参照と追加する)
    モジュール から 開発環境の準備へのリンク(ローカルサーバ)
    開発環境の準備の最後に ローカルサーバの説明を入れる(移す。ajax と todo から 開発環境の準備へリンク)
        開発環境の準備にローカルサーバ立ち上げの説明を集約

**Comment by azu** [comment]
モジュールは移動するだけ。
先頭に注記を入れたい

**Comment by lacolaco** [comment]
- 名前付き
  - エクスポート
  - インポート
- デフォルト
  - エクスポート
  - インポート
- すべてをインポート
- 再エクスポート
- 副作用インポート

**Comment by azu** [comment]
https://github.com/asciidwango/js-primer/issues/860#issuecomment-507212219
ES Moduleの章にリネーム

**Comment by azu** [comment]
- モジュールからCommonJSを移動
- モジュールからbundlerを移動
- モジュールを移動
- モジュールのnamed,defaultの順番変更

**Comment by azu** [comment]
> モジュール -> アプリケーション開発の準備:ローカルサーバの立ち上げ
> 
>     モジュールの章で概念を学び、具体的な話はアプリケーションの開発の準備でというリンクを入れる
>     https://jsprimer.net/use-case/module/
>     モジュールの章は構文紹介してるだけというイメージを強める

#805 これどうするかな。

**Comment by azu** [comment]
後はbundlerを https://jsprimer.net/appendix/links/ に移動するだけ?

**Comment by azu** [comment]
- [ ] https://jsprimer.net/basic/module/ チェックリスト

**Comment by azu** [comment]
まとめなくてもよさそう

**Comment by lacolaco** [comment]
リファクタリングで消されたバンドラーのコラム

https://github.com/asciidwango/js-primer/blob/951027cf7b36a3dd01b2654aba39604440602ba8/source/use-case/module/README.md#%E3%82%B3%E3%83%A9%E3%83%A0-%E3%83%A2%E3%82%B8%E3%83%A5%E3%83%BC%E3%83%AB%E3%83%90%E3%83%B3%E3%83%89%E3%83%A9%E3%83%BC-module-bundler

**Comment by azu** [comment]
#925 に移行してこれでモジュールは閉じる
