### ISSUE TITLE
ユースケースに目次とdescriptionを追加する

### ISSUE THREAD

**Issue by azu** [asciidwango/js-primer#676]
From https://github.com/asciidwango/js-primer/issues/669#issuecomment-466978725

- ユースケースの各章にdescriptionを追加
- 次のページにそれぞれ目次ライクな表示を追加
- [jsprimer.net/use-case/](https://jsprimer.net/use-case/)
- [jsprimer.net/use-case/ajaxapp](https://jsprimer.net/use-case/ajaxapp/)
- [jsprimer.net/use-case/nodecli](https://jsprimer.net/use-case/nodecli/)
- [jsprimer.net/use-case/todoapp](https://jsprimer.net/use-case/todoapp/)

## Tasks

- [x] descriptionの追加
  - [x] [jsprimer.net/use-case/ajaxapp](https://jsprimer.net/use-case/ajaxapp/) @lacolaco 
  - [x] [jsprimer.net/use-case/nodecli](https://jsprimer.net/use-case/nodecli/) @lacolaco 
  - [x] [jsprimer.net/use-case/todoapp](https://jsprimer.net/use-case/todoapp/) @azu 
- [x] 目次の追加
  - https://github.com/asciidwango/js-primer/blob/master/tools/generate-summary-1.js を追加するか変更する
