### ISSUE TITLE
All: typeof 演算子の結果と被る変数名は避ける

### ISSUE THREAD

**Issue by azu** [asciidwango/js-primer#804]
#803 

JavaScriptに詳しくない人はキーワード/リテラルの区別が難しいという問題があり、
シンタックスハイライトが効いてない環境(書籍も含め)では、次のようなコードで`string`に特別な意味があるように感じてしまうという話があった。

```js
const string = new String("文字列");
```

これは、`typeof` 演算子の結果で  `string`, `number`, `object`、`function` などがあるためではという話になった。
そのため、`typeof` 演算子の結果文字列として出てくるものは変数名として使うことを避けるようにする。

## Tasks

- [x] <https://jsprimer.net/basic/wrapper-object/#primitive-type-and-wrapper-object> は `const string = new String("String");` 自体が良くないので修正
- [x] `string`, `number`, `object`、`function`、(`boolean`)、`symbol` をさける
  - typeofにもでてくるので特別な意味がありそうな変数名に見える
  - `str`, `num`, `obj`、`fn`、`symbolKey`、booleanはisとかhasとかに変更する
  - OK: `array`, `error` (typeofにはないから、文字列"array"はビルトインではでてこないため)
- [ ] CONTRIBUTING.md とかにルールを追加する

具体的には次のように変更する。

```diff
- const string = new String("String");
+ const str = new String("文字列");
```

**Comment by azu** [comment]
https://eslint.org/docs/rules/id-blacklist を入れる

```js
// LICENSE : MIT
"use strict";
module.exports = {
    "env": {
        "es6": true,
        "node": true,
        "browser": true,
        "jquery": true,
        "mocha": true
    },
    "parserOptions": {
        "ecmaVersion": 2018,
        "sourceType": "module"
    },
    "rules": {
        "id-blacklist": ["error", "string", "number", "object", "function", "boolean", "symbol"],
        "indent": [
            "error", 4, {
                "SwitchCase": 1
            }
        ],
        "quotes": ["error", "double", { "allowTemplateLiterals": true }],
        "array-bracket-spacing": [
            "error",
            "never"
        ],
        "brace-style": [
            "error",
            "1tbs"
        ],
        "block-spacing": "error",
        "comma-spacing": "error",
        "computed-property-spacing": "error",
        "no-whitespace-before-property": "error",
        // Object
        "object-curly-newline": ["off", "always"],
        "object-curly-spacing": ["error", "always"],
        "key-spacing": "error",
        "keyword-spacing": "error",
        "linebreak-style": ["error", "unix"],
        "no-multiple-empty-lines": "error",
        "rest-spread-spacing": "error",
        "semi": ["error", "always"],
        "semi-spacing": "error",
        "space-before-blocks": "error",
        "space-before-function-paren": ["error", "never"],
        "space-in-parens": "error",
        "space-infix-ops": "error",
        "space-unary-ops": "error",
        "spaced-comment": [
            "error", "always", {
                "exceptions": ["-", "=", "!"],
                "markers": [
                    "eslint",
                    "eslint-env",
                    "eslint-disable",
                    "eslint-enable",
                    "eslint-disable-line",
                    "eslint-disable-next-line",
                    "exported",
                    "globals",
                    "istanbul",
                    "!"
                ]
            }
        ],
        // const
        "prefer-const": "error",
        "no-var": "error"
    }
};

```

**Comment by azu** [comment]
> CONTRIBUTING.md とかにルールを追加する

これ忘れてた

**Comment by azu** [comment]
まあツール書いてあるからいいか
