### ISSUE TITLE
アプリケーション開発の準備 に ローカルサーバの立ち上げ方法を追加する

### ISSUE THREAD

**Issue by azu** [asciidwango/js-primer#805]
#803 

https://jsprimer.net/use-case/setup-local-env/

依存関係が多いので、整理する

- モジュール -> アプリケーション開発の準備:ローカルサーバの立ち上げ
- Ajax -> アプリケーション開発の準備:ローカルサーバの立ち上げ
- Todo -> アプリケーション開発の準備:ローカルサーバの立ち上げ

## Task

- [ ] アプリケーション開発の準備:ローカルサーバの立ち上げを追加する
- [ ] モジュール -> アプリケーション開発の準備:ローカルサーバの立ち上げ
	- モジュールの章で概念を学び、具体的な話はアプリケーションの開発の準備でというリンクを入れる
    - https://jsprimer.net/use-case/module/
    - モジュールの章は構文紹介してるだけというイメージを強める
- [ ] Ajax -> アプリケーション開発の準備:ローカルサーバの立ち上げ
- [ ] Todo -> アプリケーション開発の準備:ローカルサーバの立ち上げ

## Related

- モジュールの章をMathの後ろへ移動 #644

**Comment by azu** [comment]
>  アプリケーション開発の準備:ローカルサーバの立ち上げを追加する

これどういう感じに持っていくか難しいな

**Comment by azu** [comment]
>  アプリケーション開発の準備:ローカルサーバの立ち上げを追加する

これどういう感じに持っていくか難しいな

**Comment by azu** [comment]
起動方法 + 終了方法を追加する

- [ ] ローカルサーバの終了方法を追加する

> 因みに、ローカル・サーバーを終了させるのは、Ctrl+C で次のメッセージが出るので、"y" を返答することで終了します。
> https://pagain.hatenablog.com/entry/2019/06/24/120820

**Comment by azu** [comment]
- [ ] index.html というファイル名に意味があることを追加する


> 早速、FireFox に "http://localhost:3000" を指定してテストしてみましたが、「Cannot GET /」のエラー・メッセージが出て動きません。
> デバッカーを見ても、「このページにソースはありません。」と出るので、HTMLファイルを読み込めていないことが判ります。単純ですが、理由は以下の2つだと考えました。
