### ISSUE TITLE
2019-07-01のミーティングアジェンダ

### ISSUE THREAD

**Issue by azu** [asciidwango/js-primer#860]
2019年7月1日のミーティングアジェンダ

**Comment by azu** [comment]
- [x] [all: typeof 演算子の結果とか被る変数名は避ける · Issue #804 · asciidwango/js-primer](https://github.com/asciidwango/js-primer/issues/804)
- [ ] [モジュールの章を移動する · Issue #644 · asciidwango/js-primer](https://github.com/asciidwango/js-primer/issues/644)
- [ ] [アプリケーション開発の準備 に ローカルサーバの立ち上げ方法を追加する · Issue #805 · asciidwango/js-primer](https://github.com/asciidwango/js-primer/issues/805) => #845 
- [x] [変数と宣言: const, let, varの順番で解説を書きなおす · Issue #806 · asciidwango/js-primer](https://github.com/asciidwango/js-primer/issues/806)
- [ ] [strict modeについて補足/リンクを入れる · Issue #807 · asciidwango/js-primer](https://github.com/asciidwango/js-primer/issues/807)
  - ちょっと補足いれたけど
- [x] [プロトタイプオブジェクト: 章の最初に目的を入れる · Issue #809 · asciidwango/js-primer](https://github.com/asciidwango/js-primer/issues/809)
- [ ] [GCについての図がほしい · Issue #810 · asciidwango/js-primer](https://github.com/asciidwango/js-primer/issues/810)
- [x] [非同期処理: タイトルの変更 · Issue #811 · asciidwango/js-primer](https://github.com/asciidwango/js-primer/issues/811)
- [ ] [Ajax: Fetch APIベースに書き換える · Issue #812 · asciidwango/js-primer](https://github.com/asciidwango/js-primer/issues/812)
- [x] [暗黙的な型変換: 章の最初に目的を入れる · Issue #808 · asciidwango/js-primer](https://github.com/asciidwango/js-primer/issues/808)
- [ ] [All: 章の末尾をチェックリストで統一する · Issue #813 · asciidwango/js-primer](https://github.com/asciidwango/js-primer/issues/813)
  - 進行中
- [ ] [All: エラーの表記を統一する · Issue #814 · asciidwango/js-primer](https://github.com/asciidwango/js-primer/issues/814)
  - 進行中

**Comment by azu** [comment]
文字列のリファクタリング #858  のリファクタリングが思ったよりかかかった

用語も統一した。
RegExpのnamed captureを扱ってない(`regexp.groups`がでてきてない)のがちょっとだけ気がかり

* [RegExp#matchの返り値について · Issue #785 · asciidwango/js-primer](https://github.com/asciidwango/js-primer/issues/785)
* [[meta] 用語集 · Issue #231 · asciidwango/js-primer](https://github.com/asciidwango/js-primer/issues/231)
* [refactor(string): 文字列のリファクタリング by azu · Pull Request #858 · asciidwango/js-primer](https://github.com/asciidwango/js-primer/pull/858)


| 用語         | 意味                                       | 例                                    |
| ---------- | ---------------------------------------- | ------------------------------------ |
| 文字列        | Stringオブジェクトのこと                          | `"string"`                           |
| 検索文字列      | String#indexOf(検索文字列) など検索対象などに指定した文字列のこと | `"string".indexOf("検索文字列")`            |
| 置換文字列      | String#replace(検索文字列, 置換文字列) のように、replaceメソッドで`文字列`中の`検索文字列`に一致した部分を置き換える文字列 | `"string".replace("検索文字列", "置換文字列")` |
| パターン       | /パターン/ 正規表現のbodyのこと                      | `/パターン/`                             |
| フラグ        | /パターン/i の `i` や`g` などのこと                 | `/パターン/i`                            |
| パターン文字列    | new RegExp("パターン文字列") コンストラクタの場合に渡す文字列のこと。正規表現へ変換されることを想定した文字列のこと | `new RegExp("パターン文字列")`              |
| 正規表現オブジェクト | new RegExpや/パターン/ の返り値である`RegExp`のインスタンスオブジェクト | `var 正規表現オブジェクト = /パターン/フラグ`         |

**Comment by azu** [comment]
[`Array.prototype.flat` と `Array.prototype.flatMap` · Issue #847 · asciidwango/js-primer](https://github.com/asciidwango/js-primer/issues/847)

話題になったAPIだから入れたいけど、本文として入れると単に網羅性が高くなるだけでいまいちだからSmooshGateのコラムという形がいいのかなーとか思った。

- [#SmooshGate FAQ  |  Web  |  Google Developers](https://developers.google.com/web/updates/2018/03/smooshgate)

**Comment by azu** [comment]
https://github.com/asciidwango/js-primer/issues/861
ECMAScript 2019がリリースされたので最終的に入れるもの確認

**Comment by azu** [comment]
---

メモ

**Comment by azu** [comment]
モジュールは移動するだけ。
先頭に注記を入れたい

**Comment by azu** [comment]
モジュールは単体だと動かないのでやっぱりやっかりお

**Comment by azu** [comment]
📝 https://jsprimer.net/use-case/module/ には require("hoge") がどう解決されるのかが書かれていない(実際に仕様ではないんだろうけど)

**Comment by azu** [comment]
モジュール

- named export と named import
- default export と default import
- alias export と alias import?
- +

**Comment by lacolaco** [comment]
```
- 名前付き
  - エクスポート
  - インポート
- デフォルト
  - エクスポート
  - インポート
- すべてをインポート
- 再エクスポート
- 副作用インポート
```

**Comment by azu** [comment]
- 先頭にTodoアプリで実際に動かしながら学ぶため、ここでは構文の説明とモジュールのイメージを掴むのが目的です。
- モジュールを実際に動かすためには色々準備が必要なので読み飛ばして大丈夫です。
- モジュールをCommonJSをNodejs CLIの方に移動
- モジュールバンドラーを参考リンク集に移動して + webpack + rollup へのリンクを入れる

**Comment by azu** [comment]
- [x] を
- ✔
- ☑

**Comment by azu** [comment]
https://github.com/asciidwango/js-primer/issues/863

**Comment by azu** [comment]
> Aのため、Bが発生する

**Comment by azu** [comment]
https://qiita.com/tonkotsuboy_com/items/07f8ef98abf89250b90c

**Comment by azu** [comment]
`Array#flat` を

https://jsprimer.net/basic/array/
結合 -> フラット化

という感じで入れる。

- depthの説明
- array.flat => arrayになる

する。

**Comment by azu** [comment]
[【備忘録】【js-primer】タグ付きテンプレート関数がよく分からなかったので整理した - Qiita](https://qiita.com/natecotus/items/be28e1c7111270d9207d)

**Comment by azu** [comment]
ECMAScript 2019

- [ ] Flat
- [ ] 2017以降は省略 1年毎に1あがる

**Comment by azu** [comment]
https://tc39.es/

**Comment by azu** [comment]
タイトル

**Comment by azu** [comment]
> JavaScript Primer 〜サブタイトル〜

**Comment by lacolaco** [comment]
`迷わないための入門書`

**Comment by azu** [comment]
- スッキリ
- 複雑
- 迷よわないための入門書

**Comment by azu** [comment]
入れなくていい言葉

- 仕様
- モダン

**Comment by lacolaco** [comment]
`モダン` は却下

**Comment by azu** [comment]
https://github.com/progedu/after-nyobi-intro

**Comment by azu** [comment]
メインタイトルは JavaScript Primer
サブタイトルは次回

**Comment by azu** [comment]
サブタイトルのissueを作った
https://github.com/asciidwango/js-primer/issues/865

**Comment by azu** [comment]
次回8/5(月)
